name: easy_farm
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluro: ^2.0.3
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  equatable: ^2.0.0
  json_annotation: ^3.1.1
  dartz: ^0.9.2
  auto_route: ^0.6.9
  get_it: ^5.0.6
  injectable: ^1.0.7
  overlay_support: ^1.0.5
  dio: ^3.0.10
  flutter_secure_storage: ^4.1.0
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen:
  json_serializable: ^3.5.1
  injectable_generator: ^1.0.7
  auto_route_generator: ^0.6.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/easyfarm-logo-white-2.png
